#端口，项目上下文根
server:
  port: 8081
  servlet:
    context-path: /api
#配置mybatis
mybatis:
  #配置xml映射路径
  mapper-locations: classpath:mapper/*.xml
  #配置实体类的别名
  type-aliases-package: com.xyc.news.pojo
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true

#配置mysql连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsmanage?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  main:
    allow-circular-references: true
  #文件大小 MB必须大写
  #  maxFileSize 是单个文件大小
  #  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

upload:
  path: D:/
